Repository jpso2406/ZONA-44-, pull requests merged in 2025-05, with the labels that each got.

#46 Devcontainer de ruby on rails + postgres
  backend/.devcontainer/Dockerfile
  backend/.devcontainer/create-db-user.sql
  backend/.devcontainer/devcontainer.json
  backend/.devcontainer/docker-compose.yml
  backend/.kamal/hooks/docker-setup.sample
  backend/.kamal/hooks/post-app-boot.sample
  backend/.kamal/hooks/post-deploy.sample
  backend/.kamal/hooks/post-proxy-reboot.sample
  backend/.kamal/hooks/pre-app-boot.sample
  backend/.kamal/hooks/pre-build.sample
  backend/.kamal/hooks/pre-connect.sample
  backend/.kamal/hooks/pre-deploy.sample
  backend/.kamal/hooks/pre-proxy-reboot.sample
  backend/.kamal/secrets
  backend/.ruby-version
  backend/2
  backend/Dockerfile
  backend/Gemfile.lock
  backend/README.md
  backend/app/assets/images/fondo.png
  backend/app/assets/images/iconos/instagram.png
  backend/app/assets/images/iconos/whatsapp.png
  backend/app/assets/images/logo-grande.png
  backend/app/assets/images/logo.jpg
  backend/app/assets/images/platillos/hamburguesa.jpg
  backend/app/assets/images/platillos/perroscalientes.jpg
  backend/app/assets/images/platillos/salchipapas.jpg
  backend/app/assets/stylesheets/bienvenidos.css
  backend/app/assets/stylesheets/menu.css
  backend/app/assets/stylesheets/stylesheets/application.css
  backend/app/assets/stylesheets/stylesheets/bienvenidos.css
  backend/app/assets/stylesheets/stylesheets/menu.css
  backend/app/controllers/home_controller.rb
  backend/app/controllers/menu_controller.rb
  backend/app/helpers/home_helper.rb
  backend/app/helpers/menu_helper.rb
  backend/app/views/home/bienvenidos.html.erb
  backend/app/views/home/menu.html.erb
  backend/app/views/menu/hamburguesa.html.erb
  backend/app/views/menu/perrocaliente.html.erb
  backend/app/views/menu/salchipapa.html.erb
  backend/config/credentials.yml.enc
  backend/config/database.yml
  backend/config/deploy.yml
  backend/config/routes.rb
  backend/db/schema.rb
  backend/test/controllers/home_controller_test.rb
  backend/test/controllers/menu_controller_test.rb
Labels: bug

#48 menu y listas de platillos
  backend/app/assets/images/fondo.jpg
  backend/app/assets/images/iconos/instagram.png
  backend/app/assets/images/iconos/whatsapp.png
  backend/app/assets/images/logo-grande.png
  backend/app/assets/images/logo.jpg
  backend/app/assets/images/platillos/chuzo.jpg
  backend/app/assets/images/platillos/desgranado.jpg
  backend/app/assets/images/platillos/hamburguesa.jpg
  backend/app/assets/images/platillos/perroscalientes.jpg
  backend/app/assets/images/platillos/salchipapas.jpg
  backend/app/assets/images/platillos/salvajada.jpg
  backend/app/assets/stylesheets/bienvenidos.css
  backend/app/assets/stylesheets/carta.css
  backend/app/assets/stylesheets/menu.css
  backend/app/controllers/home_controller.rb
  backend/app/controllers/menus_controller.rb
  backend/app/helpers/home_helper.rb
  backend/app/helpers/menu_helper.rb
  backend/app/views/home/bienvenidos.html.erb
  backend/app/views/home/menu.html.erb
  backend/app/views/menus/chuzo.html.erb
  backend/app/views/menus/desgranados.html.erb
  backend/app/views/menus/hamburguesa.html.erb
  backend/app/views/menus/perroscalientes.html.erb
  backend/app/views/menus/salchipapas.html.erb
  backend/app/views/menus/salvajada.html.erb
  backend/config/routes.rb
  backend/test/controllers/home_controller_test.rb
  backend/test/controllers/menu_controller_test.rb
Labels: enhancement

#49 OK
  docs/css/estilo.css
  docs/index.html
Labels: enhancement

#55 Feature/55
  backend/app/assets/stylesheets/carta.css
  backend/app/controllers/carrito_controller.rb
  backend/app/helpers/carrito_helper.rb
  backend/app/views/menus/chuzo.html.erb
  backend/app/views/menus/desgranados.html.erb
  backend/app/views/menus/hamburguesa.html.erb
  backend/app/views/menus/perroscalientes.html.erb
  backend/app/views/menus/salchipapas.html.erb
  backend/app/views/menus/salvajada.html.erb
  backend/app/views/shared/_flash_modal.html.erb
  backend/config/routes.rb
  backend/test/controllers/carrito_controller_test.rb
Labels: bug

#59 terminado
  docs/css/estilo.css
  docs/css/ver.css
  docs/index.html
  docs/ver.html
Labels: enhancement

#77 Feature/76
  docs/assets/img/JeisonOrtiz.png
  docs/assets/img/JesusZambrano.png
  docs/assets/img/JosueTorres.jpg
  docs/assets/img/JuanPabloSierra.png
  docs/index.html
  docs/ver.html
Labels: enhancement

#78 listo ubicacion
  backend/app/views/home/bienvenidos.html.erb
Labels: enhancement

#86 Feature/84
  docs/assets/css/estilo.css
  docs/assets/css/ver.css
  docs/index.html
  docs/ver.html
Labels: documentation

#87 listo
  Frontend/zona44_app/lib/bloc/plato_bloc.dart
  Frontend/zona44_app/lib/bloc/plato_event.dart
  Frontend/zona44_app/lib/bloc/plato_state.dart
  Frontend/zona44_app/lib/main.dart
  Frontend/zona44_app/lib/models/plato.dart
  Frontend/zona44_app/lib/repositories/plato_repository.dart
  Frontend/zona44_app/lib/screens/categorias_screen.dart
  Frontend/zona44_app/lib/screens/platos_screen.dart
  Frontend/zona44_app/pubspec.lock
  Frontend/zona44_app/pubspec.yaml
Labels: enhancement

#91 modelos grupos
  backend/app/controllers/grupos_controller.rb
  backend/app/controllers/home_controller.rb
  backend/app/helpers/grupos_helper.rb
  backend/app/models/admin.rb
  backend/app/models/grupo.rb
  backend/app/views/admin/dashboard.html.erb
  backend/app/views/grupos/_form.html.erb
  backend/app/views/grupos/_grupo.html.erb
  backend/app/views/grupos/_grupo.json.jbuilder
  backend/app/views/grupos/edit.html.erb
  backend/app/views/grupos/index.html.erb
  backend/app/views/grupos/index.json.jbuilder
  backend/app/views/grupos/new.html.erb
  backend/app/views/grupos/show.html.erb
  backend/app/views/grupos/show.json.jbuilder
  backend/app/views/home/menu.html.erb
  backend/config/routes.rb
  backend/db/migrate/20250521193030_create_active_storage_tables.active_storage.rb
  backend/db/migrate/20250521193243_create_grupos.rb
  backend/db/schema.rb
  backend/test/controllers/grupos_controller_test.rb
  backend/test/fixtures/grupos.yml
  backend/test/models/grupo_test.rb
  backend/test/system/grupos_test.rb
Labels: enhancement

#96 error solucionado
  backend/.env
  backend/.gitignore
  backend/app/models/admin.rb
  backend/db/schema.rb
Labels: bug

#104 vista de bienvenida agregada
  templateS/app/assets/config/manifest.js
  templateS/app/assets/images/fondo.png
  templateS/app/assets/images/iconos/instagram.png
  templateS/app/assets/images/iconos/whatsapp.png
  templateS/app/assets/images/logo-grande.png
  templateS/app/assets/images/logo.jpg
  templateS/app/assets/stylesheets/bienvenidos.css
  templateS/app/assets/stylesheets/menu.css
  templateS/app/controllers/home_controller.rb
  templateS/app/helpers/home_helper.rb
  templateS/app/views/dashboards/index.html.erb
  templateS/app/views/home/bienvenida.html.erb
  templateS/app/views/layouts/base.html.erb
  templateS/app/views/layouts/partials/_footer-scripts.html.erb
  templateS/app/views/layouts/partials/_footer.html.erb
  templateS/app/views/layouts/partials/_head-css.html.erb
  templateS/app/views/layouts/partials/_horizontal-nav.html.erb
  templateS/app/views/layouts/partials/_page-title.html.erb
  templateS/app/views/layouts/partials/_right-sidebar.html.erb
  templateS/app/views/layouts/partials/_sidenav.html.erb
  templateS/app/views/layouts/partials/_title-meta.html.erb
  templateS/app/views/layouts/partials/_topbar.html.erb
  templateS/app/views/layouts/vertical.html.erb
  templateS/app/views/layouts_eg/boxed.html.erb
  templateS/app/views/layouts_eg/footer_fixed.html.erb
  templateS/config/routes.rb
  templateS/test/controllers/home_controller_test.rb
Labels: dependencies
