Repository jpso2406/ZONA-44-, pull requests merged in 2025-07, with the labels that each got.

#191 Feature/186
  backend/app/assets/images/animaciones/fire-loader.gif
  backend/app/assets/stylesheets/new.css
  backend/app/views/devise/sessions/new.html.erb
Labels: enhancement

#208 Feature/195
  backend/app/controllers/productos_controller.rb
  backend/app/models/adicional.rb
  backend/app/models/producto.rb
  backend/app/models/producto_adicional.rb
  backend/app/views/productos/_form.html.erb
  backend/app/views/productos/_producto.html.erb
  backend/db/migrate/20250710222414_create_producto_adicionales.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/test/fixtures/producto_adicionals.yml
  backend/test/models/producto_adicional_test.rb
Labels: enhancement

#218 Agregue los archivos de tipo pdf a la plantilla actual
  docs/assets/Fichasdecasodeuso/ficha_caso_de_uso_ADMIN.pdf
  docs/assets/Fichasdecasodeuso/ficha_caso_de_uso_EMPLEADO.pdf
  docs/assets/Fichasdecasodeuso/ficha_caso_uso.pdf
  docs/assets/Mackup/Mackup Zona44.pdf
  docs/assets/Mackup/Mackup movil.pdf
  docs/assets/diagramas/DiagramaER_2.0.pdf
  docs/assets/diagramas/Diagrama_caso_de_uso.pdf
  docs/assets/diagramas/Diagrama_caso_uso_ADMIN.pdf
  docs/assets/diagramas/Diagrama_caso_uso_EMPLEADO.pdf
  docs/assets/diagramas/Diagrama_clases_2.0.pdf
  docs/assets/srs/SRS_Zona44.pdf
  docs/index.html
Labels: documentation, enhancement

#234 mover casos de usos a carpeta diagramas
  docs/index.html
Labels: documentation

#235 listo
  backend/app/views/admin/_producto_card.html.erb
  backend/app/views/productos/_producto.html.erb
  backend/db/seeds.rb
Labels: bug
